import React, { useCallback, useEffect, useState } from "react";
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  SafeAreaView,
  ScrollView,
  TextInput,
  Alert,
  Platform,
  Image,
  ActivityIndicator,
} from "react-native";
import DateTimePicker from "@react-native-community/datetimepicker";
import * as Notifications from "expo-notifications";

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldPlaySound: true,
    shouldSetBadge: false,
    shouldShowBanner: true,
    shouldShowList: true,
  }),
});

import {
  ArrowLeft,
  Plus,
  Trash2,
  CalendarHeart,
  Pencil,
  X,
  Bell,
} from "lucide-react-native";
import { useThemeContext } from "../styles/ThemeContext";
import { useLanguageContext } from "../styles/LanguageContext";
import { getCelebrationImage } from "../utils/celebrationImage";
import { api } from "../app/api";

export type CustomAnniversary = {
  id: string;
  title: string;
  date: string; // yyyy-mm-dd
  reminder?: string;
  reminderDaysBefore?: number;
};

const REMINDER_OPTIONS = [
  { value: 0, labelKey: "anniversary.reminderSameDay" },
  { value: 1, labelKey: "anniversary.reminder1Day" },
  { value: 3, labelKey: "anniversary.reminder3Days" },
  { value: 7, labelKey: "anniversary.reminder7Days" },
];

/** Auto-generate reminder text based on anniversary title */
function autoReminder(title: string, t: (k: string) => string): string {
  const lower = title.toLowerCase();
  if (
    lower.includes("birthday") || lower.includes("生日")
  ) {
    return t("anniversary.autoReminderBirthday");
  }
  if (
    lower.includes("anniversary") ||
    lower.includes("纪念")
  ) {
    return t("anniversary.autoReminderAnniversary");
  }
  if (
    lower.includes("date") ||
    lower.includes("约会") ||
    lower.includes("first") ||
    lower.includes("第一")
  ) {
    return t("anniversary.autoReminderDate");
  }
  return t("anniversary.autoReminderDefault").replace("{title}", title);
}

function formatDate(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${dd}`;
}

function daysFromToday(dateStr: string): number {
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const [year, month, day] = dateStr.split("-").map(Number);
  const target = new Date(year, month - 1, day);
  return Math.round(
    (target.getTime() - today.getTime()) / (1000 * 60 * 60 * 24)
  );
}

function daysUntilNextOccurrence(dateStr: string): number {
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const [, month, day] = dateStr.split("-").map(Number);
  let next = new Date(today.getFullYear(), month - 1, day);
  if (next < today) {
    next = new Date(today.getFullYear() + 1, month - 1, day);
  }
  return Math.round(
    (next.getTime() - today.getTime()) / (1000 * 60 * 60 * 24)
  );
}

function formatCountdown(
  days: number,
  t: (k: string) => string
): { text: string; isPast: boolean } {
  if (days === 0) return { text: t("anniversary.today"), isPast: false };
  if (days === 1) return { text: t("anniversary.tomorrow"), isPast: false };
  if (days > 1)
    return {
      text: t("anniversary.inDays").replace("{count}", String(days)),
      isPast: false,
    };
  return {
    text: t("anniversary.daysAgo").replace("{count}", String(Math.abs(days))),
    isPast: true,
  };
}

// ---------------------------------------------------------------------------
// Main page
// ---------------------------------------------------------------------------

export function AnniversaryPage({
  onBack,
  relationshipStartDate,
  userId,
  linkedUser,
}: {
  onBack: () => void;
  relationshipStartDate: Date | null;
  userId: string;
  linkedUser: string | null;
}) {
  const { theme } = useThemeContext();
  const { t, language } = useLanguageContext();
  const [anniversaries, setAnniversaries] = useState<CustomAnniversary[]>([]);
  const [loading, setLoading] = useState(true);

  // Form state — used for both add and edit
  const [formVisible, setFormVisible] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null); // null = add mode
  const [formTitle, setFormTitle] = useState("");
  const [formDate, setFormDate] = useState(new Date());
  const [showDatePicker, setShowDatePicker] = useState(false);
  const [formReminder, setFormReminder] = useState("");
  const [formReminderDays, setFormReminderDays] = useState(0);
  const [reminderAutoGenerated, setReminderAutoGenerated] = useState(false);
  const [reminderLoading, setReminderLoading] = useState(false);

  const loadAnniversaries = useCallback(async () => {
    if (!userId) return;
    try {
      setLoading(true);
      const serverList = await api.getAnniversaries(userId);
      setAnniversaries(
        serverList.map((s) => ({
          id: s.id,
          title: s.title,
          date: s.date,
          reminder: s.reminder_text || undefined,
          reminderDaysBefore: s.reminder_days_before,
        }))
      );
    } catch (e) {
      console.warn("Failed to load anniversaries:", e);
    } finally {
      setLoading(false);
    }
  }, [userId]);

  useEffect(() => {
    loadAnniversaries();
  }, [loadAnniversaries]);

  const handleTitleChange = (text: string) => {
    setFormTitle(text);
  };

  // Auto-generate reminder via AI when title changes (debounced, only when user stops typing)
  useEffect(() => {
    const title = formTitle.trim();
    if (title.length < 2) return;
    if (formReminder && !reminderAutoGenerated) return; // user manually edited

    const timer = setTimeout(async () => {
      try {
        setReminderLoading(true);
        const result = await api.generateReminder({
          title,
          lang: language,
        });
        setFormReminder(result);
        setReminderAutoGenerated(true);
      } catch {
        if (!formReminder) {
          setFormReminder(autoReminder(title, t));
          setReminderAutoGenerated(true);
        }
      } finally {
        setReminderLoading(false);
      }
    }, 800);

    return () => clearTimeout(timer);
  }, [formTitle]); // eslint-disable-line react-hooks/exhaustive-deps

  const handleReminderChange = (text: string) => {
    setFormReminder(text);
    setReminderAutoGenerated(false); // user manually edited
  };

  const resetForm = () => {
    setFormTitle("");
    setFormDate(new Date());
    setFormReminder("");
    setFormReminderDays(0);
    setEditingId(null);
    setFormVisible(false);
    setReminderAutoGenerated(false);
  };

  const openAddForm = () => {
    resetForm();
    setFormVisible(true);
  };

  const openEditForm = (item: CustomAnniversary) => {
    setEditingId(item.id);
    setFormTitle(item.title);
    const [y, m, d] = item.date.split("-").map(Number);
    setFormDate(new Date(y, m - 1, d));
    setFormReminder(item.reminder || "");
    setFormReminderDays(item.reminderDaysBefore ?? 0);
    setReminderAutoGenerated(false);
    setFormVisible(true);
  };

  const handleSave = async () => {
    if (!formTitle.trim() || !userId) return;
    try {
      if (editingId) {
        await api.updateAnniversary(editingId, {
          userId,
          title: formTitle.trim(),
          date: formatDate(formDate),
          reminderDaysBefore: formReminderDays,
          reminderText: formReminder.trim() || undefined,
        });
      } else {
        await api.createAnniversary({
          userId,
          title: formTitle.trim(),
          date: formatDate(formDate),
          reminderDaysBefore: formReminderDays,
          reminderText: formReminder.trim() || undefined,
        });
      }
      await loadAnniversaries();
      resetForm();
    } catch (e: any) {
      Alert.alert(t("common.error"), e.message || "Save failed");
    }
  };

  const handleDelete = (id: string) => {
    Alert.alert(
      t("anniversary.deleteConfirm"),
      t("anniversary.deleteConfirmMessage"),
      [
        { text: t("common.cancel"), style: "cancel" },
        {
          text: t("anniversary.deleteBtn"),
          style: "destructive",
          onPress: async () => {
            try {
              await api.deleteAnniversary(id, { userId });
              await loadAnniversaries();
            } catch (e: any) {
              Alert.alert(t("common.error"), e.message || "Delete failed");
            }
          },
        },
      ]
    );
  };

  const sorted = [...anniversaries].sort(
    (a, b) => daysUntilNextOccurrence(a.date) - daysUntilNextOccurrence(b.date)
  );

  const handleTestNotification = async () => {
    const { status } = await Notifications.requestPermissionsAsync();
    if (status !== "granted") {
      Alert.alert(t("common.error"), t("anniversary.notificationPermission"));
      return;
    }
    // Use the nearest upcoming anniversary's real reminder content
    const nearest = sorted[0];
    const title = nearest?.title || t("anniversary.testNotificationTitle");
    const body = nearest?.reminder || t("anniversary.testNotificationBody");
    await Notifications.scheduleNotificationAsync({
      content: { title, body },
      trigger: null,
    });
  };

  // --- Render ---
  return (
    <SafeAreaView
      style={[styles.screen, { backgroundColor: theme.colorBackground }]}
    >
      <ScrollView stickyHeaderIndices={[0]}>
        {/* Header */}
        <View
          style={[
            styles.header,
            {
              backgroundColor: theme.colorBackground,
              borderBottomColor: theme.colorBorder,
            },
          ]}
        >
          <View style={styles.headerRow}>
            <TouchableOpacity onPress={onBack} style={styles.backBtn}>
              <ArrowLeft size={22} color={theme.colorForeground} />
            </TouchableOpacity>
            <Text style={[styles.headerTitle, { color: theme.colorForeground }]}>
              {t("anniversary.pageTitle")}
            </Text>
            {linkedUser ? (
              <TouchableOpacity onPress={openAddForm} style={styles.backBtn}>
                <Plus size={22} color={theme.colorForeground} />
              </TouchableOpacity>
            ) : (
              <View style={{ width: 30 }} />
            )}
          </View>
        </View>

        <View style={styles.content}>
          {!linkedUser ? (
            <View style={styles.emptyState}>
              <CalendarHeart size={40} color={theme.colorMutedForeground} />
              <Text style={[styles.emptyTitle, { color: theme.colorForeground }]}>
                {t("anniversary.emptyTitle")}
              </Text>
              <Text style={[styles.emptyDesc, { color: theme.colorMutedForeground }]}>
                {t("anniversary.notLinked")}
              </Text>
            </View>
          ) : (
          <>
          {/* Auto milestones */}
          {relationshipStartDate && (
            <View style={{ marginBottom: 20 }}>
              <Text
                style={[
                  styles.sectionLabel,
                  { color: theme.colorMutedForeground },
                ]}
              >
                {t("anniversary.autoMilestones")}
              </Text>
              <AutoMilestoneList
                startDate={relationshipStartDate}
                theme={theme}
                t={t}
              />
            </View>
          )}

          {/* Custom section */}
          <Text
            style={[
              styles.sectionLabel,
              { color: theme.colorMutedForeground },
            ]}
          >
            {t("anniversary.customTitle")}
          </Text>

          {loading && (
            <View style={{ alignItems: "center", paddingVertical: 40 }}>
              <ActivityIndicator size="large" color={theme.colorPrimary} />
            </View>
          )}

          {!loading && sorted.length === 0 && !formVisible && (
            <TouchableOpacity
              style={[
                styles.emptyCard,
                {
                  backgroundColor: theme.colorSecondary,
                  borderColor: theme.colorBorder,
                },
              ]}
              onPress={openAddForm}
              activeOpacity={0.7}
            >
              <CalendarHeart size={40} color={theme.colorMutedForeground} />
              <Text
                style={[styles.emptyTitle, { color: theme.colorForeground }]}
              >
                {t("anniversary.emptyTitle")}
              </Text>
              <Text
                style={[
                  styles.emptyDesc,
                  { color: theme.colorMutedForeground },
                ]}
              >
                {t("anniversary.emptyDesc")}
              </Text>
            </TouchableOpacity>
          )}

          {sorted.map((item) => (
            <AnniversaryItem
              key={item.id}
              item={item}
              onEdit={openEditForm}
              onDelete={handleDelete}
              theme={theme}
              t={t}
              language={language}
            />
          ))}

          {/* Add / Edit form */}
          {formVisible && (
            <View
              style={[
                styles.addForm,
                {
                  backgroundColor: theme.colorCard,
                  borderColor: theme.colorBorder,
                },
              ]}
            >
              <View style={styles.addFormHeader}>
                <Text
                  style={[
                    styles.addFormTitle,
                    { color: theme.colorForeground },
                  ]}
                >
                  {editingId
                    ? t("anniversary.editTitle")
                    : t("anniversary.addTitle")}
                </Text>
                <TouchableOpacity
                  onPress={resetForm}
                  style={styles.iconBtnSmall}
                >
                  <X size={18} color={theme.colorMutedForeground} />
                </TouchableOpacity>
              </View>

              {/* Name */}
              <Text
                style={[
                  styles.inputLabel,
                  { color: theme.colorMutedForeground },
                ]}
              >
                {t("anniversary.nameLabel")}
              </Text>
              <TextInput
                style={[
                  styles.input,
                  {
                    backgroundColor: theme.colorInputBackground,
                    color: theme.colorForeground,
                    borderColor: theme.colorBorder,
                  },
                ]}
                value={formTitle}
                onChangeText={handleTitleChange}
                placeholder={t("anniversary.namePlaceholder")}
                placeholderTextColor={theme.colorMutedForeground}
              />

              {/* Date */}
              <Text
                style={[
                  styles.inputLabel,
                  { color: theme.colorMutedForeground },
                ]}
              >
                {t("anniversary.dateLabel")}
              </Text>
              <TouchableOpacity
                style={[
                  styles.dateButton,
                  {
                    backgroundColor: theme.colorInputBackground,
                    borderColor: theme.colorBorder,
                  },
                ]}
                onPress={() => setShowDatePicker(true)}
              >
                <Text style={{ color: theme.colorForeground, fontSize: 15 }}>
                  {formatDate(formDate)}
                </Text>
              </TouchableOpacity>
              {showDatePicker && (
                <DateTimePicker
                  value={formDate}
                  mode="date"
                  display={Platform.OS === "ios" ? "spinner" : "default"}
                  onChange={(_, date) => {
                    if (Platform.OS !== "ios") setShowDatePicker(false);
                    if (date) setFormDate(date);
                  }}
                />
              )}
              {showDatePicker && Platform.OS === "ios" && (
                <TouchableOpacity
                  onPress={() => setShowDatePicker(false)}
                  style={[
                    styles.confirmDateBtn,
                    { backgroundColor: theme.colorPrimary },
                  ]}
                >
                  <Text
                    style={{
                      color: theme.colorPrimaryForeground,
                      fontWeight: "600",
                    }}
                  >
                    {t("anniversary.confirmDate")}
                  </Text>
                </TouchableOpacity>
              )}

              {/* Reminder text */}
              <Text
                style={[
                  styles.inputLabel,
                  { color: theme.colorMutedForeground },
                ]}
              >
                {t("anniversary.reminderLabel")}
              </Text>
              <TextInput
                style={[
                  styles.input,
                  {
                    backgroundColor: theme.colorInputBackground,
                    color: theme.colorForeground,
                    borderColor: theme.colorBorder,
                  },
                ]}
                value={formReminder}
                onChangeText={handleReminderChange}
                placeholder={t("anniversary.reminderPlaceholder")}
                placeholderTextColor={theme.colorMutedForeground}
              />

              {/* Reminder time */}
              <Text
                style={[
                  styles.inputLabel,
                  { color: theme.colorMutedForeground },
                ]}
              >
                {t("anniversary.reminderTimeLabel")}
              </Text>
              <View style={styles.reminderOptions}>
                {REMINDER_OPTIONS.map((opt) => {
                  const selected = formReminderDays === opt.value;
                  return (
                    <TouchableOpacity
                      key={opt.value}
                      style={[
                        styles.reminderChip,
                        {
                          backgroundColor: selected
                            ? theme.colorPrimary
                            : theme.colorInputBackground,
                          borderColor: selected
                            ? theme.colorPrimary
                            : theme.colorBorder,
                        },
                      ]}
                      onPress={() => setFormReminderDays(opt.value)}
                      activeOpacity={0.7}
                    >
                      <Text
                        style={[
                          styles.reminderChipText,
                          {
                            color: selected
                              ? theme.colorPrimaryForeground
                              : theme.colorForeground,
                          },
                        ]}
                      >
                        {t(opt.labelKey)}
                      </Text>
                    </TouchableOpacity>
                  );
                })}
              </View>

              {/* Save */}
              <TouchableOpacity
                style={[
                  styles.saveBtn,
                  {
                    backgroundColor: theme.colorPrimary,
                    opacity: formTitle.trim() ? 1 : 0.5,
                  },
                ]}
                onPress={handleSave}
                disabled={!formTitle.trim()}
                activeOpacity={0.7}
              >
                <Text
                  style={[
                    styles.saveBtnText,
                    { color: theme.colorPrimaryForeground },
                  ]}
                >
                  {editingId
                    ? t("anniversary.updateBtn")
                    : t("anniversary.saveBtn")}
                </Text>
              </TouchableOpacity>

              {/* Test notification */}
              <TouchableOpacity
                style={[
                  styles.testBtn,
                  { borderColor: theme.colorBorder },
                ]}
                onPress={handleTestNotification}
                activeOpacity={0.7}
              >
                <Bell size={16} color={theme.colorMutedForeground} />
                <Text
                  style={[
                    styles.testBtnText,
                    { color: theme.colorMutedForeground },
                  ]}
                >
                  {t("anniversary.testNotification")}
                </Text>
              </TouchableOpacity>
            </View>
          )}
          </>
          )}
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

// ---------------------------------------------------------------------------
// AnniversaryItem
// ---------------------------------------------------------------------------

function AnniversaryItem({
  item,
  onEdit,
  onDelete,
  theme,
  t,
  language,
}: {
  item: CustomAnniversary;
  onEdit: (item: CustomAnniversary) => void;
  onDelete: (id: string) => void;
  theme: any;
  t: (key: string) => string;
  language: string;
}) {
  const days = daysFromToday(item.date);
  const isToday = days === 0;
  const { text: countdownText, isPast } = formatCountdown(days, t);

  const [celebrationImageUri, setCelebrationImageUri] = useState<string | null>(null);
  const [imageLoading, setImageLoading] = useState(false);

  useEffect(() => {
    if (!isToday) return;
    let cancelled = false;
    setImageLoading(true);
    getCelebrationImage(item.title, language)
      .then((uri) => {
        if (!cancelled) setCelebrationImageUri(uri);
      })
      .finally(() => {
        if (!cancelled) setImageLoading(false);
      });
    return () => { cancelled = true; };
  }, [isToday, item.title, language]);

  return (
    <TouchableOpacity
      style={[
        styles.itemCard,
        { backgroundColor: theme.colorCard, borderColor: theme.colorBorder },
        isToday && { flexDirection: "column" as const },
      ]}
      onPress={() => onEdit(item)}
      activeOpacity={0.7}
    >
      {isToday && (
        <View style={styles.itemCelebrationBanner}>
          {celebrationImageUri ? (
            <Image
              source={{ uri: celebrationImageUri }}
              style={styles.itemCelebrationImage}
              resizeMode="cover"
            />
          ) : (
            <View
              style={[
                styles.itemCelebrationPlaceholder,
                { backgroundColor: theme.colorPrimary + "20" },
              ]}
            >
              {imageLoading && (
                <ActivityIndicator size="small" color={theme.colorPrimary} />
              )}
            </View>
          )}
        </View>
      )}
      <View style={isToday ? styles.itemRowWrap : { flexDirection: "row" as const, alignItems: "center" as const, flex: 1 }}>
        <View style={styles.itemContent}>
          <Text style={[styles.itemTitle, { color: theme.colorForeground }]}>
            {item.title}
          </Text>
          <Text style={[styles.itemDate, { color: theme.colorMutedForeground }]}>
            {item.date}
          </Text>
          {item.reminder ? (
            <Text
              style={[styles.itemReminder, { color: theme.colorMutedForeground }]}
              numberOfLines={1}
            >
              {item.reminder}
            </Text>
          ) : null}
        </View>
        <View style={styles.itemRight}>
          <Text
            style={[
              styles.itemCountdown,
              {
                color: isPast
                  ? theme.colorMutedForeground
                  : theme.colorPrimary,
              },
            ]}
          >
            {countdownText}
          </Text>
          <View style={styles.itemActions}>
            <TouchableOpacity
              onPress={() => onEdit(item)}
              style={styles.actionIcon}
              hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
            >
              <Pencil size={15} color={theme.colorPrimary} />
            </TouchableOpacity>
            <TouchableOpacity
              onPress={() => onDelete(item.id)}
              style={styles.actionIcon}
              hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
            >
              <Trash2 size={15} color={theme.colorDestructive} />
            </TouchableOpacity>
          </View>
        </View>
      </View>
    </TouchableOpacity>
  );
}

// ---------------------------------------------------------------------------
// AutoMilestoneList
// ---------------------------------------------------------------------------

function AutoMilestoneList({
  startDate,
  theme,
  t,
}: {
  startDate: Date;
  theme: any;
  t: (key: string) => string;
}) {
  const today = new Date();
  const todayDate = new Date(
    today.getFullYear(),
    today.getMonth(),
    today.getDate()
  );
  const startUTC = Date.UTC(
    startDate.getFullYear(),
    startDate.getMonth(),
    startDate.getDate()
  );
  const nowUTC = Date.UTC(
    todayDate.getFullYear(),
    todayDate.getMonth(),
    todayDate.getDate()
  );
  const daysTogether = Math.max(
    0,
    Math.round((nowUTC - startUTC) / (1000 * 60 * 60 * 24))
  );

  const milestones: { label: string; daysUntil: number }[] = [];

  const next100 = (Math.floor(daysTogether / 100) + 1) * 100;
  milestones.push({
    label: t("anniversary.day100").replace("{count}", String(next100)),
    daysUntil: next100 - daysTogether,
  });

  const startDay = startDate.getDate();
  let monthCandidate = new Date(
    todayDate.getFullYear(),
    todayDate.getMonth(),
    startDay
  );
  if (monthCandidate.getDate() !== startDay) {
    monthCandidate = new Date(
      todayDate.getFullYear(),
      todayDate.getMonth() + 1,
      0
    );
  }
  if (monthCandidate <= todayDate) {
    monthCandidate = new Date(
      todayDate.getFullYear(),
      todayDate.getMonth() + 1,
      startDay
    );
    if (monthCandidate.getDate() !== startDay) {
      monthCandidate = new Date(
        todayDate.getFullYear(),
        todayDate.getMonth() + 2,
        0
      );
    }
  }
  const monthsDiff =
    (monthCandidate.getFullYear() - startDate.getFullYear()) * 12 +
    (monthCandidate.getMonth() - startDate.getMonth());
  if (monthsDiff > 0 && monthsDiff % 12 !== 0) {
    milestones.push({
      label: t("anniversary.monthlyAnniversary").replace(
        "{count}",
        String(monthsDiff)
      ),
      daysUntil: Math.round(
        (monthCandidate.getTime() - todayDate.getTime()) /
          (1000 * 60 * 60 * 24)
      ),
    });
  }

  let nextYear = new Date(
    todayDate.getFullYear(),
    startDate.getMonth(),
    startDate.getDate()
  );
  if (nextYear <= todayDate) {
    nextYear = new Date(
      todayDate.getFullYear() + 1,
      startDate.getMonth(),
      startDate.getDate()
    );
  }
  const yearsDiff = nextYear.getFullYear() - startDate.getFullYear();
  if (yearsDiff > 0) {
    milestones.push({
      label: t("anniversary.yearlyAnniversary").replace(
        "{count}",
        String(yearsDiff)
      ),
      daysUntil: Math.round(
        (nextYear.getTime() - todayDate.getTime()) / (1000 * 60 * 60 * 24)
      ),
    });
  }

  milestones.sort((a, b) => a.daysUntil - b.daysUntil);

  return (
    <>
      {milestones.map((m, i) => {
        const { text } = formatCountdown(m.daysUntil, t);
        return (
          <View
            key={i}
            style={[
              styles.milestoneRow,
              { backgroundColor: theme.colorSecondary },
            ]}
          >
            <Text
              style={[
                styles.milestoneLabel,
                { color: theme.colorForeground },
              ]}
            >
              {m.label}
            </Text>
            <Text
              style={[
                styles.milestoneCountdown,
                { color: theme.colorMutedForeground },
              ]}
            >
              {text}
            </Text>
          </View>
        );
      })}
    </>
  );
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = StyleSheet.create({
  screen: { flex: 1 },
  header: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backBtn: { padding: 4 },
  headerTitle: { fontSize: 17, fontWeight: "600" },
  iconBtnSmall: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
    gap: 12,
  },
  content: { paddingHorizontal: 20, paddingVertical: 16 },
  sectionLabel: {
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 10,
  },
  emptyCard: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: "dashed" as any,
    gap: 12,
  },
  emptyTitle: { fontSize: 16, fontWeight: "600" },
  emptyDesc: { fontSize: 14 },
  itemCard: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderWidth: StyleSheet.hairlineWidth,
  },
  itemCelebrationBanner: {
    width: "100%",
    marginBottom: 10,
  },
  itemCelebrationImage: {
    width: "100%",
    height: 100,
    borderRadius: 12,
  },
  itemCelebrationPlaceholder: {
    width: "100%",
    height: 100,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  itemRowWrap: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
  },
  itemContent: { flex: 1, gap: 4 },
  itemTitle: { fontSize: 15, fontWeight: "600" },
  itemDate: { fontSize: 12 },
  itemReminder: { fontSize: 12, marginTop: 2 },
  itemRight: { alignItems: "flex-end", gap: 8 },
  itemCountdown: { fontSize: 13, fontWeight: "600" },
  itemActions: { flexDirection: "row", gap: 12 },
  actionIcon: { padding: 4 },
  milestoneRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginBottom: 6,
  },
  milestoneLabel: { fontSize: 14, flex: 1 },
  milestoneCountdown: { fontSize: 12, marginLeft: 8 },
  addForm: {
    borderRadius: 14,
    padding: 14,
    marginTop: 12,
    borderWidth: StyleSheet.hairlineWidth,
    gap: 10,
  },
  addFormHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  addFormTitle: { fontSize: 16, fontWeight: "700" },
  inputLabel: { fontSize: 13, fontWeight: "500" },
  input: {
    borderRadius: 10,
    padding: 12,
    fontSize: 15,
    borderWidth: StyleSheet.hairlineWidth,
  },
  dateButton: {
    borderRadius: 10,
    padding: 12,
    borderWidth: StyleSheet.hairlineWidth,
  },
  confirmDateBtn: {
    alignSelf: "center",
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 8,
    marginTop: 4,
  },
  reminderOptions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  reminderChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
  },
  reminderChipText: { fontSize: 13, fontWeight: "500" },
  saveBtn: {
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 4,
  },
  saveBtnText: { fontSize: 15, fontWeight: "600" },
  testBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 12,
    paddingVertical: 12,
    borderWidth: StyleSheet.hairlineWidth,
  },
  testBtnText: { fontSize: 13, fontWeight: "500" },
});
